version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
      include: scope
    groups:
      actions:
        patterns:
          - '*'
